# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = X:\GIT\Umbra2D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = X:\GIT\Umbra2D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install\local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local

# Special rule for the target install/local
install\local\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local\fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install\fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components\fast: list_install_components

.PHONY : list_install_components\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start X:\GIT\Umbra2D\CMakeFiles X:\GIT\Umbra2D\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start X:\GIT\Umbra2D\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Umbra2D

# Build rule for target.
Umbra2D: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) Umbra2D
.PHONY : Umbra2D

# fast build rule for target.
Umbra2D\fast:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\build
.PHONY : Umbra2D\fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall\fast:
	$(MAKE) -f Dependencies\Vendor\glfw\CMakeFiles\uninstall.dir\build.make /nologo -$(MAKEFLAGS) Dependencies\Vendor\glfw\CMakeFiles\uninstall.dir\build
.PHONY : uninstall\fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) glfw
.PHONY : glfw

# fast build rule for target.
glfw\fast:
	$(MAKE) -f Dependencies\Vendor\glfw\src\CMakeFiles\glfw.dir\build.make /nologo -$(MAKEFLAGS) Dependencies\Vendor\glfw\src\CMakeFiles\glfw.dir\build
.PHONY : glfw\fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings\fast:
	$(MAKE) -f Dependencies\Vendor\glfw\src\CMakeFiles\update_mappings.dir\build.make /nologo -$(MAKEFLAGS) Dependencies\Vendor\glfw\src\CMakeFiles\update_mappings.dir\build
.PHONY : update_mappings\fast

#=============================================================================
# Target rules for targets named glad-generate-files

# Build rule for target.
glad-generate-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) glad-generate-files
.PHONY : glad-generate-files

# fast build rule for target.
glad-generate-files\fast:
	$(MAKE) -f Dependencies\Vendor\glad\CMakeFiles\glad-generate-files.dir\build.make /nologo -$(MAKEFLAGS) Dependencies\Vendor\glad\CMakeFiles\glad-generate-files.dir\build
.PHONY : glad-generate-files\fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) glad
.PHONY : glad

# fast build rule for target.
glad\fast:
	$(MAKE) -f Dependencies\Vendor\glad\CMakeFiles\glad.dir\build.make /nologo -$(MAKEFLAGS) Dependencies\Vendor\glad\CMakeFiles\glad.dir\build
.PHONY : glad\fast

Dependencies\Source\AssetLibrary.obj: Dependencies\Source\AssetLibrary.cpp.obj

.PHONY : Dependencies\Source\AssetLibrary.obj

# target to build an object file
Dependencies\Source\AssetLibrary.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\AssetLibrary.cpp.obj
.PHONY : Dependencies\Source\AssetLibrary.cpp.obj

Dependencies\Source\AssetLibrary.i: Dependencies\Source\AssetLibrary.cpp.i

.PHONY : Dependencies\Source\AssetLibrary.i

# target to preprocess a source file
Dependencies\Source\AssetLibrary.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\AssetLibrary.cpp.i
.PHONY : Dependencies\Source\AssetLibrary.cpp.i

Dependencies\Source\AssetLibrary.s: Dependencies\Source\AssetLibrary.cpp.s

.PHONY : Dependencies\Source\AssetLibrary.s

# target to generate assembly for a file
Dependencies\Source\AssetLibrary.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\AssetLibrary.cpp.s
.PHONY : Dependencies\Source\AssetLibrary.cpp.s

Dependencies\Source\Camera.obj: Dependencies\Source\Camera.cpp.obj

.PHONY : Dependencies\Source\Camera.obj

# target to build an object file
Dependencies\Source\Camera.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Camera.cpp.obj
.PHONY : Dependencies\Source\Camera.cpp.obj

Dependencies\Source\Camera.i: Dependencies\Source\Camera.cpp.i

.PHONY : Dependencies\Source\Camera.i

# target to preprocess a source file
Dependencies\Source\Camera.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Camera.cpp.i
.PHONY : Dependencies\Source\Camera.cpp.i

Dependencies\Source\Camera.s: Dependencies\Source\Camera.cpp.s

.PHONY : Dependencies\Source\Camera.s

# target to generate assembly for a file
Dependencies\Source\Camera.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Camera.cpp.s
.PHONY : Dependencies\Source\Camera.cpp.s

Dependencies\Source\Colliders.obj: Dependencies\Source\Colliders.cpp.obj

.PHONY : Dependencies\Source\Colliders.obj

# target to build an object file
Dependencies\Source\Colliders.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Colliders.cpp.obj
.PHONY : Dependencies\Source\Colliders.cpp.obj

Dependencies\Source\Colliders.i: Dependencies\Source\Colliders.cpp.i

.PHONY : Dependencies\Source\Colliders.i

# target to preprocess a source file
Dependencies\Source\Colliders.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Colliders.cpp.i
.PHONY : Dependencies\Source\Colliders.cpp.i

Dependencies\Source\Colliders.s: Dependencies\Source\Colliders.cpp.s

.PHONY : Dependencies\Source\Colliders.s

# target to generate assembly for a file
Dependencies\Source\Colliders.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Colliders.cpp.s
.PHONY : Dependencies\Source\Colliders.cpp.s

Dependencies\Source\Entity.obj: Dependencies\Source\Entity.cpp.obj

.PHONY : Dependencies\Source\Entity.obj

# target to build an object file
Dependencies\Source\Entity.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Entity.cpp.obj
.PHONY : Dependencies\Source\Entity.cpp.obj

Dependencies\Source\Entity.i: Dependencies\Source\Entity.cpp.i

.PHONY : Dependencies\Source\Entity.i

# target to preprocess a source file
Dependencies\Source\Entity.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Entity.cpp.i
.PHONY : Dependencies\Source\Entity.cpp.i

Dependencies\Source\Entity.s: Dependencies\Source\Entity.cpp.s

.PHONY : Dependencies\Source\Entity.s

# target to generate assembly for a file
Dependencies\Source\Entity.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Entity.cpp.s
.PHONY : Dependencies\Source\Entity.cpp.s

Dependencies\Source\Gui.obj: Dependencies\Source\Gui.cpp.obj

.PHONY : Dependencies\Source\Gui.obj

# target to build an object file
Dependencies\Source\Gui.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Gui.cpp.obj
.PHONY : Dependencies\Source\Gui.cpp.obj

Dependencies\Source\Gui.i: Dependencies\Source\Gui.cpp.i

.PHONY : Dependencies\Source\Gui.i

# target to preprocess a source file
Dependencies\Source\Gui.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Gui.cpp.i
.PHONY : Dependencies\Source\Gui.cpp.i

Dependencies\Source\Gui.s: Dependencies\Source\Gui.cpp.s

.PHONY : Dependencies\Source\Gui.s

# target to generate assembly for a file
Dependencies\Source\Gui.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Gui.cpp.s
.PHONY : Dependencies\Source\Gui.cpp.s

Dependencies\Source\Main.obj: Dependencies\Source\Main.cpp.obj

.PHONY : Dependencies\Source\Main.obj

# target to build an object file
Dependencies\Source\Main.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Main.cpp.obj
.PHONY : Dependencies\Source\Main.cpp.obj

Dependencies\Source\Main.i: Dependencies\Source\Main.cpp.i

.PHONY : Dependencies\Source\Main.i

# target to preprocess a source file
Dependencies\Source\Main.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Main.cpp.i
.PHONY : Dependencies\Source\Main.cpp.i

Dependencies\Source\Main.s: Dependencies\Source\Main.cpp.s

.PHONY : Dependencies\Source\Main.s

# target to generate assembly for a file
Dependencies\Source\Main.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Main.cpp.s
.PHONY : Dependencies\Source\Main.cpp.s

Dependencies\Source\Quad.obj: Dependencies\Source\Quad.cpp.obj

.PHONY : Dependencies\Source\Quad.obj

# target to build an object file
Dependencies\Source\Quad.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Quad.cpp.obj
.PHONY : Dependencies\Source\Quad.cpp.obj

Dependencies\Source\Quad.i: Dependencies\Source\Quad.cpp.i

.PHONY : Dependencies\Source\Quad.i

# target to preprocess a source file
Dependencies\Source\Quad.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Quad.cpp.i
.PHONY : Dependencies\Source\Quad.cpp.i

Dependencies\Source\Quad.s: Dependencies\Source\Quad.cpp.s

.PHONY : Dependencies\Source\Quad.s

# target to generate assembly for a file
Dependencies\Source\Quad.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Quad.cpp.s
.PHONY : Dependencies\Source\Quad.cpp.s

Dependencies\Source\Shader.obj: Dependencies\Source\Shader.cpp.obj

.PHONY : Dependencies\Source\Shader.obj

# target to build an object file
Dependencies\Source\Shader.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Shader.cpp.obj
.PHONY : Dependencies\Source\Shader.cpp.obj

Dependencies\Source\Shader.i: Dependencies\Source\Shader.cpp.i

.PHONY : Dependencies\Source\Shader.i

# target to preprocess a source file
Dependencies\Source\Shader.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Shader.cpp.i
.PHONY : Dependencies\Source\Shader.cpp.i

Dependencies\Source\Shader.s: Dependencies\Source\Shader.cpp.s

.PHONY : Dependencies\Source\Shader.s

# target to generate assembly for a file
Dependencies\Source\Shader.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Shader.cpp.s
.PHONY : Dependencies\Source\Shader.cpp.s

Dependencies\Source\Texture.obj: Dependencies\Source\Texture.cpp.obj

.PHONY : Dependencies\Source\Texture.obj

# target to build an object file
Dependencies\Source\Texture.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Texture.cpp.obj
.PHONY : Dependencies\Source\Texture.cpp.obj

Dependencies\Source\Texture.i: Dependencies\Source\Texture.cpp.i

.PHONY : Dependencies\Source\Texture.i

# target to preprocess a source file
Dependencies\Source\Texture.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Texture.cpp.i
.PHONY : Dependencies\Source\Texture.cpp.i

Dependencies\Source\Texture.s: Dependencies\Source\Texture.cpp.s

.PHONY : Dependencies\Source\Texture.s

# target to generate assembly for a file
Dependencies\Source\Texture.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Texture.cpp.s
.PHONY : Dependencies\Source\Texture.cpp.s

Dependencies\Source\Window.obj: Dependencies\Source\Window.cpp.obj

.PHONY : Dependencies\Source\Window.obj

# target to build an object file
Dependencies\Source\Window.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Window.cpp.obj
.PHONY : Dependencies\Source\Window.cpp.obj

Dependencies\Source\Window.i: Dependencies\Source\Window.cpp.i

.PHONY : Dependencies\Source\Window.i

# target to preprocess a source file
Dependencies\Source\Window.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Window.cpp.i
.PHONY : Dependencies\Source\Window.cpp.i

Dependencies\Source\Window.s: Dependencies\Source\Window.cpp.s

.PHONY : Dependencies\Source\Window.s

# target to generate assembly for a file
Dependencies\Source\Window.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Source\Window.cpp.s
.PHONY : Dependencies\Source\Window.cpp.s

Dependencies\Vendor\glad\src\glad.obj: Dependencies\Vendor\glad\src\glad.c.obj

.PHONY : Dependencies\Vendor\glad\src\glad.obj

# target to build an object file
Dependencies\Vendor\glad\src\glad.c.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\glad\src\glad.c.obj
.PHONY : Dependencies\Vendor\glad\src\glad.c.obj

Dependencies\Vendor\glad\src\glad.i: Dependencies\Vendor\glad\src\glad.c.i

.PHONY : Dependencies\Vendor\glad\src\glad.i

# target to preprocess a source file
Dependencies\Vendor\glad\src\glad.c.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\glad\src\glad.c.i
.PHONY : Dependencies\Vendor\glad\src\glad.c.i

Dependencies\Vendor\glad\src\glad.s: Dependencies\Vendor\glad\src\glad.c.s

.PHONY : Dependencies\Vendor\glad\src\glad.s

# target to generate assembly for a file
Dependencies\Vendor\glad\src\glad.c.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\glad\src\glad.c.s
.PHONY : Dependencies\Vendor\glad\src\glad.c.s

Dependencies\Vendor\imgui\backends\imgui_impl_glfw.obj: Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.obj

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.obj

# target to build an object file
Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.obj
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.obj

Dependencies\Vendor\imgui\backends\imgui_impl_glfw.i: Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.i

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.i

# target to preprocess a source file
Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.i
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.i

Dependencies\Vendor\imgui\backends\imgui_impl_glfw.s: Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.s

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.s
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.s

Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.obj: Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.obj

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.obj

# target to build an object file
Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.obj
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.obj

Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.i: Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.i

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.i

# target to preprocess a source file
Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.i
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.i

Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.s: Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.s

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.s
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.s

Dependencies\Vendor\imgui\imgui.obj: Dependencies\Vendor\imgui\imgui.cpp.obj

.PHONY : Dependencies\Vendor\imgui\imgui.obj

# target to build an object file
Dependencies\Vendor\imgui\imgui.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui.cpp.obj
.PHONY : Dependencies\Vendor\imgui\imgui.cpp.obj

Dependencies\Vendor\imgui\imgui.i: Dependencies\Vendor\imgui\imgui.cpp.i

.PHONY : Dependencies\Vendor\imgui\imgui.i

# target to preprocess a source file
Dependencies\Vendor\imgui\imgui.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui.cpp.i
.PHONY : Dependencies\Vendor\imgui\imgui.cpp.i

Dependencies\Vendor\imgui\imgui.s: Dependencies\Vendor\imgui\imgui.cpp.s

.PHONY : Dependencies\Vendor\imgui\imgui.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\imgui.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui.cpp.s
.PHONY : Dependencies\Vendor\imgui\imgui.cpp.s

Dependencies\Vendor\imgui\imgui_demo.obj: Dependencies\Vendor\imgui\imgui_demo.cpp.obj

.PHONY : Dependencies\Vendor\imgui\imgui_demo.obj

# target to build an object file
Dependencies\Vendor\imgui\imgui_demo.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_demo.cpp.obj
.PHONY : Dependencies\Vendor\imgui\imgui_demo.cpp.obj

Dependencies\Vendor\imgui\imgui_demo.i: Dependencies\Vendor\imgui\imgui_demo.cpp.i

.PHONY : Dependencies\Vendor\imgui\imgui_demo.i

# target to preprocess a source file
Dependencies\Vendor\imgui\imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_demo.cpp.i
.PHONY : Dependencies\Vendor\imgui\imgui_demo.cpp.i

Dependencies\Vendor\imgui\imgui_demo.s: Dependencies\Vendor\imgui\imgui_demo.cpp.s

.PHONY : Dependencies\Vendor\imgui\imgui_demo.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_demo.cpp.s
.PHONY : Dependencies\Vendor\imgui\imgui_demo.cpp.s

Dependencies\Vendor\imgui\imgui_draw.obj: Dependencies\Vendor\imgui\imgui_draw.cpp.obj

.PHONY : Dependencies\Vendor\imgui\imgui_draw.obj

# target to build an object file
Dependencies\Vendor\imgui\imgui_draw.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_draw.cpp.obj
.PHONY : Dependencies\Vendor\imgui\imgui_draw.cpp.obj

Dependencies\Vendor\imgui\imgui_draw.i: Dependencies\Vendor\imgui\imgui_draw.cpp.i

.PHONY : Dependencies\Vendor\imgui\imgui_draw.i

# target to preprocess a source file
Dependencies\Vendor\imgui\imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_draw.cpp.i
.PHONY : Dependencies\Vendor\imgui\imgui_draw.cpp.i

Dependencies\Vendor\imgui\imgui_draw.s: Dependencies\Vendor\imgui\imgui_draw.cpp.s

.PHONY : Dependencies\Vendor\imgui\imgui_draw.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_draw.cpp.s
.PHONY : Dependencies\Vendor\imgui\imgui_draw.cpp.s

Dependencies\Vendor\imgui\imgui_tables.obj: Dependencies\Vendor\imgui\imgui_tables.cpp.obj

.PHONY : Dependencies\Vendor\imgui\imgui_tables.obj

# target to build an object file
Dependencies\Vendor\imgui\imgui_tables.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_tables.cpp.obj
.PHONY : Dependencies\Vendor\imgui\imgui_tables.cpp.obj

Dependencies\Vendor\imgui\imgui_tables.i: Dependencies\Vendor\imgui\imgui_tables.cpp.i

.PHONY : Dependencies\Vendor\imgui\imgui_tables.i

# target to preprocess a source file
Dependencies\Vendor\imgui\imgui_tables.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_tables.cpp.i
.PHONY : Dependencies\Vendor\imgui\imgui_tables.cpp.i

Dependencies\Vendor\imgui\imgui_tables.s: Dependencies\Vendor\imgui\imgui_tables.cpp.s

.PHONY : Dependencies\Vendor\imgui\imgui_tables.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\imgui_tables.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_tables.cpp.s
.PHONY : Dependencies\Vendor\imgui\imgui_tables.cpp.s

Dependencies\Vendor\imgui\imgui_widgets.obj: Dependencies\Vendor\imgui\imgui_widgets.cpp.obj

.PHONY : Dependencies\Vendor\imgui\imgui_widgets.obj

# target to build an object file
Dependencies\Vendor\imgui\imgui_widgets.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_widgets.cpp.obj
.PHONY : Dependencies\Vendor\imgui\imgui_widgets.cpp.obj

Dependencies\Vendor\imgui\imgui_widgets.i: Dependencies\Vendor\imgui\imgui_widgets.cpp.i

.PHONY : Dependencies\Vendor\imgui\imgui_widgets.i

# target to preprocess a source file
Dependencies\Vendor\imgui\imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_widgets.cpp.i
.PHONY : Dependencies\Vendor\imgui\imgui_widgets.cpp.i

Dependencies\Vendor\imgui\imgui_widgets.s: Dependencies\Vendor\imgui\imgui_widgets.cpp.s

.PHONY : Dependencies\Vendor\imgui\imgui_widgets.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\imgui_widgets.cpp.s
.PHONY : Dependencies\Vendor\imgui\imgui_widgets.cpp.s

Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.obj: Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.obj

.PHONY : Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.obj

# target to build an object file
Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.obj:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.obj
.PHONY : Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.obj

Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.i: Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.i

.PHONY : Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.i

# target to preprocess a source file
Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.i:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.i
.PHONY : Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.i

Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.s: Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.s

.PHONY : Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.s:
	$(MAKE) -f CMakeFiles\Umbra2D.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Umbra2D.dir\Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.s
.PHONY : Dependencies\Vendor\imgui\misc\cpp\imgui_stdlib.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... Umbra2D
	@echo ... install/local
	@echo ... install
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... list_install_components
	@echo ... uninstall
	@echo ... glfw
	@echo ... update_mappings
	@echo ... glad-generate-files
	@echo ... glad
	@echo ... Dependencies/Source/AssetLibrary.obj
	@echo ... Dependencies/Source/AssetLibrary.i
	@echo ... Dependencies/Source/AssetLibrary.s
	@echo ... Dependencies/Source/Camera.obj
	@echo ... Dependencies/Source/Camera.i
	@echo ... Dependencies/Source/Camera.s
	@echo ... Dependencies/Source/Colliders.obj
	@echo ... Dependencies/Source/Colliders.i
	@echo ... Dependencies/Source/Colliders.s
	@echo ... Dependencies/Source/Entity.obj
	@echo ... Dependencies/Source/Entity.i
	@echo ... Dependencies/Source/Entity.s
	@echo ... Dependencies/Source/Gui.obj
	@echo ... Dependencies/Source/Gui.i
	@echo ... Dependencies/Source/Gui.s
	@echo ... Dependencies/Source/Main.obj
	@echo ... Dependencies/Source/Main.i
	@echo ... Dependencies/Source/Main.s
	@echo ... Dependencies/Source/Quad.obj
	@echo ... Dependencies/Source/Quad.i
	@echo ... Dependencies/Source/Quad.s
	@echo ... Dependencies/Source/Shader.obj
	@echo ... Dependencies/Source/Shader.i
	@echo ... Dependencies/Source/Shader.s
	@echo ... Dependencies/Source/Texture.obj
	@echo ... Dependencies/Source/Texture.i
	@echo ... Dependencies/Source/Texture.s
	@echo ... Dependencies/Source/Window.obj
	@echo ... Dependencies/Source/Window.i
	@echo ... Dependencies/Source/Window.s
	@echo ... Dependencies/Vendor/glad/src/glad.obj
	@echo ... Dependencies/Vendor/glad/src/glad.i
	@echo ... Dependencies/Vendor/glad/src/glad.s
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_glfw.obj
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_glfw.i
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_glfw.s
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_opengl3.obj
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_opengl3.i
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_opengl3.s
	@echo ... Dependencies/Vendor/imgui/imgui.obj
	@echo ... Dependencies/Vendor/imgui/imgui.i
	@echo ... Dependencies/Vendor/imgui/imgui.s
	@echo ... Dependencies/Vendor/imgui/imgui_demo.obj
	@echo ... Dependencies/Vendor/imgui/imgui_demo.i
	@echo ... Dependencies/Vendor/imgui/imgui_demo.s
	@echo ... Dependencies/Vendor/imgui/imgui_draw.obj
	@echo ... Dependencies/Vendor/imgui/imgui_draw.i
	@echo ... Dependencies/Vendor/imgui/imgui_draw.s
	@echo ... Dependencies/Vendor/imgui/imgui_tables.obj
	@echo ... Dependencies/Vendor/imgui/imgui_tables.i
	@echo ... Dependencies/Vendor/imgui/imgui_tables.s
	@echo ... Dependencies/Vendor/imgui/imgui_widgets.obj
	@echo ... Dependencies/Vendor/imgui/imgui_widgets.i
	@echo ... Dependencies/Vendor/imgui/imgui_widgets.s
	@echo ... Dependencies/Vendor/imgui/misc/cpp/imgui_stdlib.obj
	@echo ... Dependencies/Vendor/imgui/misc/cpp/imgui_stdlib.i
	@echo ... Dependencies/Vendor/imgui/misc/cpp/imgui_stdlib.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

